### ISSUE TITLE
Article links don't work as "Expected" for user (user report)

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#170]
I've marked this as a bug, but it is more like "sort-of-a-bug".  More like something that doesn't behave as expected.

PWM (former board member) pointed out that right clicking on an article title in a search, and selecting "open in another tab", does not open the article in the other tab...it just opens a the same search result view.

I was going to write back to him and say that "it would do it if you have "skip abstracts" set, because then the links should be going to the read mode page".  HOWEVER, I just tried it and it doesn't work even when you are going to skip abstracts.  

Fix: I think it should.  I do think it should only work like that if skip abstracts was set before you do the search.  Then the links behind the article titles could all point to the corresponding "read" page URL for the article, and then it would work.  Incidentally, it worked fine for an article in most cited, which normally goes to a read page.

**Comment by nrshapiro** [comment]
Something to think about: It may also be prudent to do that even if Skip Abstracts is not selected.  I'm not sure what the user would be expecting if they right clicked and said open in another tab, EXCEPT to open the article (or abstract if they are not allowed).  I doubt they would expect to see the current tab simply copied over to the new tab.

**Comment by adistasio** [comment]
@bakerac4 @napafundi This doesn't work because the a tags don't have a value. Is there a reason for this? Can we always fill out the a tag that way right clicking works as expected and the left click is handled via the javascript?

**Comment by billdami** [comment]
@adistasio the reason this doesnt work now is because the links aren't just native browser `<a>` links with a simple href="" value, they are empty because we do the custom logic (for opening the abstract pane or forwarding to the article) via an on-click listener.

But yeah, we _might_ be able to do it how you suggest, where we populate the `href=""` with the direct article link, but still prevent the default browser action on the normal left click (to handle that custom logic). An alternate, and possibly better (in regards to semantics and possibly user expectation) solution might be to instead have that link url dynamically update to either be the full article url (if the user has abstract preview turned off), or something like `/search?abtstractId={id}` where the toggling of the abstract preview is now controlled via a query param, so if you were to open that link directly, it would be the search results, with that specific article's abstract preview open. Though if having the link always point to the full article is the desired behavior then your idea is probably best.

**Comment by nrshapiro** [comment]
@billdami @adistasio  It should have the Read link embedded and the left click intercepted as needed.  The reason is 1) the behavior in any mode makes more sense to go to read, and 2) There are other options on the right click menu, like bookmark the link, which really only make sense if it's a read link.
