### ISSUE TITLE
Moving Abstract Border

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#22]
@billdami 

While it's nice to see the whole abstract, personally at least, I find the self-resizing abstract field disturbing.  If I want to browse the list of results by clicking on one by one, it jumps around, and often in the way of the next abstract I want to click.

Perhaps if the autosize button you have were a checkbox, so you could turn it on and off, that would improve the usability.  It should default to "off" though, and remember the setting I've done.  

I like that it can be manually sized, and IMO the abstract field should keep the size I set by dragging, unless it's on autosize via the checkbox.

I am still seeing a big black bar too in the bottom of the abstract
![2020-09-03_13h13_54](https://user-images.githubusercontent.com/4837554/92146213-5fe08780-ede7-11ea-8370-e9e83b3c6366.png)
.

**Comment by billdami** [comment]
@nrshapiro re: the "black bar" issue, yeah that is fixed in the latest builds, but I don't think those have been pushed to staging yet. Unfortunately I'm not sure theres a good way to expose the currently deployed builds as they result to merged changes/pull requests with our current build pipeline setup being in our private Gitlab instance.

**Comment by billdami** [comment]
The abstract pane resizing items will be resolved via #25
