### ISSUE TITLE
List of Documents that don't currently display or partially display

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#223]
This is just to list those documents which are currently not displaying at all or partially.  This can be client issue or server issue.  Notes of any source should be added to the individual entries as they are investigated or resolved.

If you fix an issue in the list, please EDIT and add text to mark the individual comment/issue FIXED.

(If you'd prefer I just individually bug these, let me know.)

**Comment by nrshapiro** [comment]
(1991) Subject Index. Conflict and Compromise: Therapeutic Implications 74:231-238

https://stage.pep-web.rocks/read/ZBK.074.0231A

**Comment by bakerac4** [comment]
@nrshapiro looking at the XML for ZBK.074.0231A - 

<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE pepkbd3 SYSTEM "http://peparchive.org/pepa1dtd/pepkbd3.dtd">
<pepkbd3><meta><revisions><revbld>a1v11</revbld><revdesc>paginated index, needed for pgx jumps</revdesc></revisions></meta><artinfo arttype="ART" j="ZBK" ISBN="0823610381" id="ZBK.074.0231A">
<artyear>1991</artyear>
<artbkinfo extract="ZBK.074.0000A" prev="ZBK.074.0219A"/>
<artvol>74</artvol>
<artpgrg style="arabic" prefixused="">231-238</artpgrg>
<arttitle id="H0016">Subject Index</arttitle>
<artauth hidden="false"><none/></artauth>
</artinfo>
<body/>

You don't have anything in the body tag since its being self closed. Would it be possible to fix that and then I try to fix on my end (the xml below that body tag is also not in the xslt file)

**Comment by nrshapiro** [comment]
@bakerac4 It's legal per the DTD...there's nothing to put in the body, though the body is required per the DTD.
Why is that a problem?  I'm not sure what I would put in there.  An empty paragraph <p/>?  I could do that if it would that help.
Yes, likely not covered by the XSLT since I just did the XSLT as a start and I didn't even think about books with indexes.

**Comment by bakerac4** [comment]
I figured the rest of the document would go in the body tags. Are the indexes not meant to do that? If so I can look into trying to figure it out without using the body - it just seemed weird to have a body and then the rest of the xml outside of that body

**Comment by nrshapiro** [comment]
The structure is in pepkbd3.dtd...the top level is per below.  There can be appendixes, bibliographies, summaries, notes, and indexes after the body (and page breaks).

<!ENTITY % summary.bib.etc  "(bib | summaries | appxs | pb | note | idx)*" >

<!ENTITY % summary.bib.etc.restricted  "(bib | summaries | appxs | idx)*" >

<!ELEMENT pepkbd3  (meta?, artinfo, tagline?, pb?, (abs, pb?)?, body, %summary.bib.etc;) >
