### ISSUE TITLE
Unceremoniously Thrown out of a New Session

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#232]
This happens reproducibly...such that I recorded a video to show it.  It's quite "startling".  This is a reproducible version of what I mentioned was happening to me this weekend as I worked on it.

1) log in to Test1
2) go to preferences
3) Click on some of the infocard options to turn on or off
...BANG...

The dialog disappears, the screen changes and you are logged out.  Never even finished with the settings in the Preferences.

Edit to Add: this just also happened to me while doing something completely different.

This is a recording of my original recording to reduce the size and get under the 10MB posting limit.

https://user-images.githubusercontent.com/4837554/104390604-1bd75f00-550c-11eb-824a-a9cb64978a52.mp4

**Comment by bakerac4** [comment]
@nrshapiro I have seen this before, however each time its been the api returning a 401 which then the front end logs you out because of. After Im done with the refactor Im working on I will take another look and confirm.

**Comment by bakerac4** [comment]
@nrshapiro I can confirm this is due to getting a 401 from the API.

<img width="1809" alt="Screen Shot 2021-01-14 at 12 10 08 PM" src="https://user-images.githubusercontent.com/9952936/104624450-95349600-5661-11eb-8656-127a0f660ce1.png">

**Comment by nrshapiro** [comment]
Ah, when you said that I didn't understand because the server does not issue 401s unless you are logging in through it.  You mean the PaDS API.  (We have two APIs)

But you are not logging in on that call, rather you are getting information about the user.  So if they are already logged in, why would you log them out?

But as far as the 401 error, assigning to James.

**Comment by bakerac4** [comment]
@nrshapiro According to the HTTP status code definition - the request has not been applied because it lacks valid authentication credentials for the target resource. We log them out because they don't have valid auth credentials for the logged in resource, which means they need to sign in again. We can see 401's when a token has expired and the client is trying to use it, or when it's not sending a token for some reason - but in all cases they need to log in again.

**Comment by jwoosnam** [comment]
@nrshapiro I think I have identified the problem here. When a user changes any setting the client immediately calls pads to save the changes and then does another call to re-read them. This is not a problem, but I did notice that if you changed them quickly enough the database was generating a concurrency error. I have now put in a change which should fix this.
In terms of a 401, I am returning this when I encounter an unexpected error and in these circumstances logging out seems fine, but should I be returning a different code?

**Comment by bakerac4** [comment]
@jwoosnam generally when its a unexpected error, you would send a 500 https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500

**Comment by billdami** [comment]
to chime in, yeah I agree with @bakerac4. Also in most cases I don't think we'd want the user to be immediately logged out if the api encountered some temporary/unexpected error, we'd want to maintain the session and instead show some sort of error feedback that the operation could not be completed.

**Comment by nrshapiro** [comment]
This is already well covered above, but in case you wanted to hear my opinion...I agree with the above.

**Comment by nrshapiro** [comment]
Should be fixed per James not returning that error code in these cases.
