### ISSUE TITLE
Favorites / Read later limits?

### ISSUE THREAD

**Issue by billdami** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#38]
@nrshapiro should the "Favorites" and "Read Later" features have any upper limit on how many documents a user can add to these lists? I don't think this was mentioned any where in the spec, but it was a question I had during our development, and seems like there probably should be one for several technical and usability concerns, so I just didn't want to forget about it as we moved along. Those concerns being:

- Storage: we are storing favorites/read later items both locally (LocalStorage) and in the user's PaDS record, and while its just document IDs, allowing a user to build up hundreds or even thousands over a long period could put strain on this storage
- API pressure: we are currently fetching all the documents to render these cards in a single search request passing all the document IDs in the GET request. A few hundred or even less document IDs could hit the max URL size for the api request. We could switch to the POST search request format and/or batch/paginate this into multiple requests eventually, but that will also add more complexity.
- Usability: The sidebar cards layout for these features isn't really setup well to displaying super long lists, if we wanted to handle displaying long lists here we'd probably have to either think about some sort of pagination/show more pattern, and/or a "View all" link that takes the user to a full fledged page to show the entire list (similar to how Most Viewed/Cited cards work).

Adding a limit for these would be fairly trivial though, and the UX for when a user hits these limits would probably amount to showing an "Sorry, you cannot save more than X favorites. Please remove some and try again." error toast notification, or something along those lines.

**Comment by nrshapiro** [comment]
@billdami  As long as you make the limit configurable in the Admin we can set it low, and increase if necessary.  

Some ways around the problems.

1) Make it 100 to start.  Use a message like you suggested to let them decide what to remove.  Note that they can also use their browsers bookmarks feature to save links.
2) Offer a preferences option to automatically roll off (discard) favorites more than 12 (user selectable) months old

The POST format is the same parameters except it can have a body, and the body format is quite easy to use.  You can still list facets and other info in the parameters.  I've been considering deprecating the GET because although I like the semantics of using GET rather than POST, the extra endpoint defs clutter up the documentation screen.  What are your thoughts on that?

Body example:

{"qtermlist":
    {   "artLevel": 1, 
        "qt" :
        [
                {
                        "field" : "art_id",
                        "words": "IJP.089.0795A OR IRP.001.0103A OR IJP.066.0447A"
                    }

        ]
    }
}

or you can use || (note that the spaces between are currently required.)

{"qtermlist":
    {   "artLevel": 1, 
        "qt" :
        [
                {
                        "field" : "art_id",
                        "words": "IJP.089.0795A || IRP.001.0103A || IJP.066.0447A"
                    }

        ]
    }
}

**Comment by billdami** [comment]
@nrshapiro while definitely doable, switching search calls from GET to POST is not super straightforward on our end. Reason is that we use an abstracted data-layer/ORM in our application framework for making most API requests, and it is RESTful, meaning it always expects `GET` for fetching/reading entities, and `POST/PUT/PATCH` creating/updating entities. So modifying this just means more customization/complexity on our end.

With that in mind, and since `GET` has been working fine for our purposes so far, I'd be hesitant to say deprecate it, at least not yet anyway.

**Comment by billdami** [comment]
@adistasio just pinging you here for PM concerns on the above discussion. Sounds like we'll likely need at least one story for adding in the basic limit restriction. And then perhaps potential additional enhancement items for down the road for Neil's other suggestions (user prefs for auto-cleaning favorites/read later items, etc).
