### ISSUE TITLE
Blank Details (Session Expired)

### ISSUE THREAD

**Issue by jwoosnam** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#384]
@adistasio 
Neil was talking on Tuesday about the client showing blank user info. This seems to be when a session has expired, but the client is still picking up a cookie.  The about box is still showing the session ID.
<img width="303" alt="Screenshot 2021-03-25 at 16 06 33" src="https://user-images.githubusercontent.com/70103034/112505856-1789b680-8d85-11eb-9278-5e915510ccd7.png">
When the client askes PaDS for the user details it returns blanks with a description of "SessionId has not been successfully logged on, so user details can't be retrieved."
<img width="214" alt="Screenshot 2021-03-25 at 16 06 54" src="https://user-images.githubusercontent.com/70103034/112505938-2cfee080-8d85-11eb-9233-efa4491cbbb7.png">

@nrshapiro (fyi)

**Comment by nrshapiro** [comment]
This is still happening, and came up in our management meeting as a priority--bumping to high priority.  Would be good to fix before beta2 starts, now slated for the 19th

**Comment by nrshapiro** [comment]
@jwoosnam  @adistasio 

The automatic logout crash in the client appears to be fixed, thanks to the 5min timeout giving us means to see it prominently.  

But to see if this Blank Details bug is fixed, we'll need to go back to a longer logout.

I think David is still interested in having people login more often (he mentioned something about statistics).  We could go for a 1 day logout--the issue I have there is because logout doesn't care if you are using the system or not, is it possible to set it for the user's local time instead?  Like 3am for everyone?  That way I think we can be pretty sure they are not using it (not positive, but pretty sure!  Even I don't typically work that late.)

For the future, but not the beta or release 1, and after further consultation with David and Nadine, we can work on making the system "usage" aware like our old system, where timeout is based on activity.  But the late night timeout should be a good workaround for quite a while, as long as we know it's not throwing someone off who is actively using the system.
