### ISSUE TITLE
Search Preview Pane - displayed content logic

### ISSUE THREAD

**Issue by billdami** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#41]
@nrshapiro I'm working on the search preview pane, and am having some trouble figuring out the exact rules for what content should displayed there and when based on the returned document and user's session/subscription, using on the spec descriptions. I'm hoping you could clear this up for me, ideally just breaking it down into a simple conditional tree of what you expect to see in each case/state.

Specifically I'm referring to these sections in the spec:

![Screen Shot 2020-09-23 at 10 08 17 AM](https://user-images.githubusercontent.com/611458/94023908-c45a8b00-fd84-11ea-9a76-4c5fb4da6bf3.png)
![Screen Shot 2020-09-23 at 10 08 39 AM](https://user-images.githubusercontent.com/611458/94023929-cb819900-fd84-11ea-8bd2-255c146d6fa5.png)

What im looking for is a simplified breakdown of this info, something along the lines of:

- When the user is LOGGED OUT:
   - When `accessClassification` is X => show this field/content: [CONTENT]
      - when the document has a `doi` => show this field/content: [CONTENT]
   - When `accessClassification` is Y => show this field/content: [CONTENT]
   - When `accessClassification` is Z => show this field/content: [CONTENT]
- When the user is LOGGED IN:
  -  When `accessLimited` is `true` => DONT show Read/Download actions, show this field/content: [CONTENT]
  -  When `accessLimited` is `false` =>: DO show Read/Download actions, show this field/content: [CONTENT]
  - etc...

Some other questions:

- Does the document's `abstract` field always get displayed?
- Spec item `#9.d.i.` mentions using the `doi` field to construct a link to http://doi.org, yet it appears this link may already be in the server returned messages like `accessLimitedDescription`, which should be used to display this?
- Spec item `#9.d.ii.` mentions that the "not logged in message" should be configurable via an AdminMode config, yet it seems a bit contradictory, as it appears this text is in the `accessLimitedDescription` field. Should only one or the other be used, or are there separate conditions for showing each (show in conditional tree if possible)?
- Re: this line in the spec: 
   > "We should add a boolean in the server to indicate if the original is available as a documentListItem field of the return data so this" 
   
   -- this would be highly desirable on our end if you are able to add that.

**Comment by nrshapiro** [comment]
@billdami 

It's actually much easier than it sounds.  Assuming you ask the server for full-text data in the parameters, it makes the decision for you.  Most of the parameters you see are intended for you to provide an explanation to the user about why they can't see a document.

First, it doesn't matter whether the user is logged in or not.  The rules are the same as far as the server is concerned.  
I'll explain below.   First a clarifying definition: When I say full-text, I mean a full-document.

1) For the Search Endpoint, you can't bring back full-text (at least currently).  Only abstracts and excerpts.  Whether you are logged in or not, without any permissions needed, EVERYONE can see the abstract (or an excerpt when there's no abstract).  Any time, every time.
   a) The `accessClassification` fields are there to tell you what the user can do (whether logged in or not, since some documents are open access).  
   b) The `accessLimited` field is the only one that matters.  The rest are explanatory.  If `accessLimited` is TRUE, then they are able to request the full-text of the document in the v2/Document endpoints (download, read, etc.)  This is only set for your software to know whether to offer full-text access buttons...see #2 to see why.

2) If you request the full-text of a document, using any of the other v2/Document endpoints other than Abstract, and the current user is not logged in, or the current user does not have permission, the server just won't give it to you.  The document field will be empty, or it will contain the abstract only.  [See Note]

_**Note**: I thought I changed this behavior since it is a waste of bandwidth to send the abstract in two fields, and the client simply has to look at the document field to see there's nothing there, and present the abstract.  But I just tested this in the interactive docs and It looks like it still does this.   I won't guarantee it stays that way forever, but we can discuss.  Perhaps it's wasteful but easier, because you can always just present the `document` field and it will either be an abstract or the document, depending on access permissions._ 

### So the rule is simple for all users:
  1) For a search, use the `accessLimited` field to decide whether to show buttons to read/download the full-text.  False means they have access, True means they do not.  IN ALL CASES.  Archive, Current, Free, etc.
  2) For document request endpoints, if you request it and for _whatever reason_ the user doesn't really have permission, the `document` field will be empty or missing, but the abstract will be provided in the `abstract` field.
  3) To explain to the user what happened if there's no document, you use the other AccessLimited fields.  The server gives you the predicates to decide what to tell the user.  And then it goes a step further to give you user messages,  That's optional.  For a multlanguage interface, you may want to code your own messages with the option to change them per l10n or whatever standard you follow.  

#### Option 1.  Roll your own message.  Good for localization.
   1) The only predicate value you need besides `accessLimited ` is `accessLimitedCurrentContent`.  But this is not to determine access...it's to help the app and thus the client understand why access was denied by the server.  It tells you why `accessLimited` is True even for a logged in user.  The data is embargoed.  You can compose your own message to include the reason, all the information to write an intelligent and helpful message is included:  
- `accessClassification` tells you the collection it's in: e.g., Archive, Current, Free.  
- If `accessLimitedCurrentContent` is True, it's embargoed by the publisher. 
- `accessLimitedPubLink` will give you a link to the material on the publishers site, or a link to the publisher site
- Sometimes a doi for the article is all we have, that takes you to the article as well,  in field `doi`.
 2) In case `accessLimited` is True (no access) but `accessLimitedCurrentContent` is False (not embargoed), this means that the user doesn't have a valid subscription, or the user is not logged in.  Either way.  In this case,  you know it's `accessLimited` and not current content, so you can write your own message to say that and encourage them to log in (roll your own).  The convenience message `accessLimitedReason` will say something like 'This is a summary excerpt from the full text of the document. The full content of the document is available to subscribers. '   It doesn't care about login, but the user might, a good reason to roll your own.

#### Option 2. Use the convenience message.
   1) `accessLimitedDescription` will tell you something similar to "The full content of the document is embargoed per an agreement with the publisher. "  This is just _convenience text_ for the client app explaining what accessLimited means.  In cases where access is not limited, it will say something like "You have access to this document"
   2) `accessLimitedReason` will give more information relating to the user, something like: 'This is a summary excerpt from the full text of the document. The full content of the document is embargoed per an agreement with the publisher. '  If there's a link to the publisher available, it will be appended at the end of this.

You can start by using the convenience messages, and then roll your own later as you better understand permissions.

Hope that helps.

**Comment by billdami** [comment]
> b) The accessLimited field is the only one that matters. The rest are explanatory. If accessLimited is **TRUE**, then they are able to request the full-text of the document in the v2/Document endpoints (download, read, etc.) This is only set for your software to know whether to offer full-text access buttons

@nrshapiro I'm assuming you mean false here? This looks like it contradicts the info further down: 
> For a search, use the accessLimited field to decide whether to show buttons to read/download the full-text. **False means they have access, True means they do not.**

which is more in line with what I was expecting.

**Comment by billdami** [comment]
But yeah, otherwise that makes a lot more sense now, thanks! I think for now for simplicity's sake we'll start with using the convenience messages, and then once we need to enable full multilingual support in Rel.2, we will refactor to use the more granular access-related fields/data to dynamically construct localized messages.

**Comment by nrshapiro** [comment]
> > b) The accessLimited field is the only one that matters. The rest are explanatory. If accessLimited is **TRUE**, then they are able to request the full-text of the document in the v2/Document endpoints (download, read, etc.) This is only set for your software to know whether to offer full-text access buttons
> 
> @nrshapiro I'm assuming you mean false here? This looks like it contradicts the info further down:
> 
> > For a search, use the accessLimited field to decide whether to show buttons to read/download the full-text. **False means they have access, True means they do not.**
> 
> which is more in line with what I was expecting.

@billdami 
Yes, it's just an error in what I just wrote.  I'm going to correct it above, since the explanation otherwise is pretty thorough.
