### ISSUE TITLE
Boolean Search is not supported in fields

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#46]
The client currently does not allow flexible booleans except in the SmartSearch field per the spec.

For example, suppose the user wants to search for Dog or Cat within a dream?  I enter: Dog or Cat there, and the search submitted is:
    `dreams_xml:("dog or cat"~25)`

I understand the search within paragraph requirement is for terms to be encapsulated that way, but if a boolean is entered, you need to see that and not look for proximity.  OR's do not fit into proximity in this way.

This should have simply been submitted as:
   `dreams_xml:(dog or cat)`

or potentially if someone enters:

dog or cat and mouse

The question is whether to do cat and mouse as proximity, e.g.,
   `dreams_xml:(dog or "cat mouse"~25)`

or as a simple boolean in the field:
   `dreams_xml:(dog or cat and mouse)`

that latter approach ignores the proximity requirement, and I'm not sure if this is really acceptable.  

This does require you to do some parsing of input on the front end which I imagine can potentially be complicated.  I've been trying to think of a better way to handle it on the backend.  I'm continuing to think about it, but happy to discuss any ideas you have.

One other idea, but it's more cumbersome, is to add an "[or]" icon, to the fields, so that users could do ORs across multiple fields instead (and, is already baked in).  This would be somewhat cumbersome to enter, but it's semantically clear.  (The OR icon could be done sort of like the ? you have now, so it would not take up much room.

Discussion?  Ideas?

**Comment by billdami** [comment]
@nrshapiro I don't necessarily think that parsing the input would be overly complex (we are already doing some simple parsing in order to apply the above mentioned `~25` proximity syntax, etc), and that may a viable solution here, as long as rules for how to parse/manipulate the text are clear-cut and consistent for every situation. Its when you start getting into more "fuzzy logic" or complex natural language processing parsing of input that it becomes a troublesome to do so on the clientside. Alternately, moving ALL of this parsing/manipulation to the api-side before sending it to Solr (kind of like you do for SmartSearch), and just having the client-side send the raw input for these fields, is another way to go.

If we do do client-side parsing, can you provide a detailed set of rules/conditions for how we should parse/manipulate the input values to cover all cases? If we can get that, I think this should be pretty doable. I'm just thinking of corner cases and such we want to be aware of, e.g.: the user intends to use the literal word "or" as part of the input (maybe its a word in a Title), not the boolean operator. Though I guess if they used quotes around the phrase like they should be, that particular case is a non-issue, but just making sure we cover all those kinds of scenarios.

I personally would probably be a bit leery of having a field/toggle in the UI for this if we can help it. The search form UI is already quite complex and those search term controls are particularly densely packed, between the "?" help icon, field label, field type dropdown, and remove button. Its a lot to fit in that relatively small sidebar layout, especially when considering mobile/phones, and trying to keep touch/tap targets decently sized/spaced for accessibility.  

One way to offset not having an in-UI control, would be to teach the syntax more in the help tooltips (like you already do with quotes for phrases, etc), and/or add another "general help tips" help icon elsewhere in the form (maybe next to the "Find terms or phrases" heading text for that section).

**Comment by nrshapiro** [comment]
@billdami 

**Solution!**  It turns out that the GVPi interface is not doing paragraph search, EXCEPT when you specify para as the field.

So we have that already covered, in a more general way.  Smartsearch works for that.  (And technically, if it turns out to be beneficial to move smartsearch elsewhere (mainly because I want to do more sophisticated things with it than just the handful of tricks it currently has), we can cover that as well by replacing it with a field which just uses paratext / parascope.)  But if we do, we would just use Doc for that, OR make it the only field that does paragraph level in any zone.  That would work in tandem with the other boxes, as long as they don't try to do true paragraph searching.

So:
1) Drop the proximity wrapper ""~25 from all input.  Not needed.
2) Let them use the top box, smartsearch, to enter words or phrases.  These will do true paragraph searches.  The entry here goes in smarttext.  
3) The other search boxes can also be used.  They will be zoned by the pulldown, but searches will not be paragraph based.

Ok, but what if they just want to search in Dreams?  They can: the results will not be different than present day PEP-Web (PD PEP-Web), because it's clearly not doing proximity search.  Try this as proof.  Search for `sandy beaches` in dreams in the new client.  You don't get any matches.  Search on PEP-Web.  You get one match.  The words are in a dream, but they are not in the same paragraph.  Once we remove the ""~25 wrapper in the new client, the result will be the same.

So: @billdami : Action item.  Please remove the ""~25 you've been adding to clauses in fulltext1.  HOWEVER: please make sure to surround any muli-word field entry by ().  E.g., the notation should be `dreams_xml:(Sandy beaches)`  If the user were to type in the dreams field: Sandy beaches or blue ocean, then you should submit `dreams_xml:(Sandy beaches or blue ocean)` to ensure that both words are applied to dreams_xml.  This isn't necessary though if the user puts them in quotes (though it doesn't hurt to do it anyway, i.e., they might write `"Sandy beaches"` which can be submitted as `dreams_xml:("sandy beaches")` or just `dreams_xml:(sandy beaches)`

**Comment by nrshapiro** [comment]
Note: While I still think this is the potential solution, in testing smartsearches against PEP-Web, the proximity based search may actually be better than a paragraph search, because the results show the hits together.  Paragraph based search can have significantly more entries because I don't think Solr cares about the word order, and the proximity search does (or at least appears to).  And because proximity search is what GVPi did, the results are almost identical to the old system.  

I still think the client should not surround the terms--but I may change smartsearch to use proximity rather than true paragraph based search.  It's helpful to be able to experiment via the client.

**Comment by nrshapiro** [comment]
@billdami @adistasio @bakerac4 

This should be fixed, on the server side, as of 2020.1202.1, for all text search fields.  I think there are still potential boolean syntax issues, so I'm leaving it open for now and I'm working on enhancing my test suite to cover more ground in this respect.

**Comment by bakerac4** [comment]
@nrshapiro can this be closed?
