### ISSUE TITLE
Search menu link resets search; the menu buttons should be like "tabs" instead

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#53]
Clicking the search menu button at the top should take you back to the search "view", but not reset your search information.  The "buttons" on that menu are basically a tab control to move among the views per the spec.  (And Read is missing from the menu).

FWIW, while the back to search does the function as well, but requires that you scroll back to the top of the center pane to get to it.  And there's no reason to lose your context when moving among the "buttons" for the views at the top.

That is per the description in the spec.

**Comment by billdami** [comment]
@nrshapiro the changes to the top nav links were intentional on our part, as the design of that area as a global site navigation bar rather than a "tabs"-like layout, lends itself to a user expectation that clicking on any of the links will behave as a "fresh open" of that page, rather than a "back to"  type operation. We could certainly change the 'Search' link to be sticky and retain the last entered search information (though using other UI patterns within the page content layouts, like more "<- Back to search" links in the other pages, like we already have in the Read view could lessen the need for this).

Regarding the omission of the 'Read' link from the top nav was also a conscious design decision, in part because of the points mentioned above, but also because it did not look like the Read page had its own "empty/landing" view defined (at least not that I could see in the spec). In other words, if you came into the app fresh and immediately clicked the 'Read' link, what should be shown? Should it just be a duplicate of the empty Search page, or maybe something like Browse? I think we'd need this empty landing state/view defined in order to have that link, as dynamically hiding it from the main nav if there is no previously viewed document would be even worse from a UX standpoint I think.

> but requires that you scroll back to the top of the center pane to get to it

yeah this behavior is more of a bug, which we can definitely fix.

**Comment by nrshapiro** [comment]
@billdami 

You've implemented the Search menu/button which really has the same problem.  The display of a "clean slate" search page is pretty stark.  Personally, I'd initially use the same info there as when they first hit the site.  Or you could provide a way in admin for us to define a full page of help/info there where we could provide instructions for search.

I think the solution, except for the very first visit, is to retain the last state of the tab.  Since the tabs are controlled entirely by information in URL, this should be easy to do, just storing it in a cookie, or the user's information area on PaDS.  

For the read button, initially, before the user has read anything, the top Read button can be there and disabled.  

This is how our site works currently (though it doesn't have the state memory, which I think will be a nice touch, especially for phone users.).

**Comment by bakerac4** [comment]
I believe this is fixed. @nrshapiro can you close if your satisfied?

**Comment by nrshapiro** [comment]
It doesn't clear anymore...closing.
