### ISSUE TITLE
IJPOpen pre-print message on article pages

### ISSUE THREAD

**Issue by rickardnyman** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#590]
We need to display a message to the user on IJPOpen article pages that these are pre-prints and not yet peer reviewed.

Can we have a banner at the top, perhaps in a different colour with a message that can be edited? Possibly just below the journal logo

**Comment by nrshapiro** [comment]
@rickardnyman  Why don't we just add it to the journal banner? (we can make it as tall as we need)?

**Comment by bakerac4** [comment]
@nrshapiro is there anything for me to do here? Or you just adding it to the banner

**Comment by nrshapiro** [comment]
Need input from @rickardnyman  on that.

Personally, I think we can do it in the banner.  

Note that it's quite easy to change the text in the banner--and the design of it is flexible, but here's a quick design (noting that the actual text wanted has yet to be supplied by D. Tuckett.):

![bannerIJPOpenLogoWithSubtitle](https://user-images.githubusercontent.com/4837554/148569382-d61e1c07-2353-44da-baca-812220141725.gif)

**Comment by nrshapiro** [comment]
@rickardnyman 

Samples on Stage now.  Again, we can change the message to whatever DT wants (within reason for length)

Note: I didn't say "these are pre-prints and not yet peer reviewed." because that looked a bit redundant given the running head (which was already on the banner: "Open Peer Review and Debate")

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/4837554/148604416-2f5e039d-c241-41bc-a305-19fc3d1318a8.png">

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/4837554/148604466-1f55e6fd-e2be-4ecb-bc0b-260971831f28.png">

For refence, the old logo was:

![bannerIJPOpenLogo (Original)](https://user-images.githubusercontent.com/4837554/148604611-e18361a3-36c7-465c-8220-06d016cb209a.gif)

My redesign is just a placeholder.  You can make it whatever you like.

**Comment by rickardnyman** [comment]
This does look like an elegant solution to me. Will check with David T

**Comment by rickardnyman** [comment]
@nrshapiro - confirmed that this is a good solution.
