### ISSUE TITLE
Pop-ups for Glossary linked words need containing to just the hyperlinked word.

### ISSUE THREAD

**Issue by SophieMBennett** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#663]
See user feedback: https://github.com/Psychoanalytic-Electronic-Publishing/Support/issues/362

A glossary pop-up should only open when the user clicks on the hyperlinked word. Currently the pop-up opens when a user clicks anywhere within the paragraph containing the word. This issue is also relevant to the translation concordance pop-ups if they contain a hyperlinked glossary term. 

Therefore, pop-ups for Glossary linked words need to be contained to just the hyperlinked word.

**Comment by SophieMBennett** [comment]
@ocappello Hi Orazio, Just flagging this issue as it is collecting user feedback in the support thread. Full details here: https://github.com/Psychoanalytic-Electronic-Publishing/Support/issues/362 The glossary pop-ups used to work fine, i.e. when the user clicked on the relevant hyperlinked word, but now the pop-up activates if you click anywhere in the paragraph containing the word, or try to select segments of text for copy/paste etc. Overall the pop-ups are currently way more active with this bug and affecting user experience.

**Comment by SophieMBennett** [comment]
@ocappello @jordanallen-dev This is an annoying bug which is drawing a bit of user feedback and would be good to investigate.

**Comment by nrshapiro** [comment]
@ocappello @jordanallen-dev 

You might consider this easy change instead:

https://github.com/Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface/issues/695

**Comment by jordanallen-dev** [comment]
> @ocappello @jordanallen-dev
> 
> You might consider this easy change instead:
> 
> #695

I might be mistaken, so please correct me if I'm wrong but it looks like your suggestion is about generating a better info card whereas Sophie is talking about article click behaviour itself

In the issue Sophie is talking about, users are having a glossary popup displayed to them whenever they click anywhere on a paragraph that contains a glossary entry - even if they don't click on the glossary term itself

The way I see it, we want to address both what Sophie is talking about and what you are suggesting as separate pieces of work

**Comment by nrshapiro** [comment]
@jordanallen-dev 

I'm addressing the problem Sophie mentioned precisely, because per my discussion with DT before, the linking of terms in the document is unnecessary, since we have the glossary infocard.  However, before I made that change to the server, you could not have the infocard without the links in the document.  Now you can.

So the suggested change is:
1) Turn off all linking of glossary entries by the server.  Now just a setting during the building of EXP_ARCH1's.
2) Turn on the setting where the table of glossary terms is sent with the XML to the client.
3) Modify the client to use that information to generate the infocard, instead of counting links.

**Comment by jordanallen-dev** [comment]
> @jordanallen-dev
> 
> I'm addressing the problem Sophie mentioned precisely, because per my discussion with DT before, the linking of terms in the document is unnecessary, since we have the glossary infocard. However, before I made that change to the server, you could not have the infocard without the links in the document. Now you can.
> 
> So the suggested change is:
> 
> 1. Turn off all linking of glossary entries by the server.  Now just a setting during the building of EXP_ARCH1's.
> 2. Turn on the setting where the table of glossary terms is sent with the XML to the client.
> 3. Modify the client to use that information to generate the infocard, instead of counting links.

Got it, makes sense

Thanks for the clarity. Your solution does sound good 

In terms of the original cause:

It looks this issue was introduced about 7 months ago with the addition of a change that tries to find the "closest" clickable element

In this case we have the glossary <a> tags inside the paragraph <p> tags:

```
<p>
    <a/>
</p>

```
When a user clicks on the paragraph itself, and no clickable event is found, it searches its children and finds the the glossary <a> tag. It then triggers that tag's behaviour instead

This was added because, quote, "Safari will sometimes get a different target than chrome, so we try to find the closest data type or type data attribute and use that"

**Comment by jordanallen-dev** [comment]
I think it was done to fix this

https://github.com/Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface/issues/633

**Comment by jordanallen-dev** [comment]
Conversation continued in https://github.com/Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface/issues/695
