### ISSUE TITLE
Top level in TOC

### ISSUE THREAD

**Issue by davidtuckett** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#666]
A possibly unintended consequnece of solutions adopted to allow  herading in jiurnal TOC's is illustrated ijn the attached. Can we somehiw suppress this? 
![Screenshot 2022-09-04 at 11 28 26 (2)](https://user-images.githubusercontent.com/70531237/188309032-d02e4368-7064-4fb2-bd8d-ce5305b9f9b0.png)

**Comment by nrshapiro** [comment]
Yes, this is ugly, and needs to be fixed ASAP.  I added the Top Level headings in the response from the server per the request of Gavant when they needed to sort out issues with repeat of journal headings here [TOC Volume Listing (Section Heading Issue)](https://github.com/Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface/issues/460) as a side effect of the TOC "fixes" done by Gavant https://github.com/Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface/issues/460.

Toward the end of the issue, on June 29, I reported this to them.  Like all issues that require Gavant action, it is assigned to @ocappello to initiate/resolve.  Another one I think is very ugly and in user's faces I more recently found is the error with the Whats New emails, which don't include volume and issue numbers for the new journals under the banner/headings, and which have page range repeated in the article listing instead of volume/issue there, so in no place can you tell what volume number or issue number is being released.  This bug is under the server issues because it's part of the DevOps service code by Gavant for that: https://github.com/Psychoanalytic-Electronic-Publishing/OpenPubArchive-Content-Server/issues/170.  Also assigned to @ocappello.

Back to the TopLevel issue, I can try to remove the TopLevel in the server, but I'd have to see whether Gavant's actually used those as they requested.  Perhaps not, since they are showing.

**Comment by bakerac4** [comment]
Fixed in #670
